### ISSUE TITLE
Úkoly z deváté lekce, machine learning

### ISSUE THREAD

**Issue by Hedwika** [Hedwika/python-032021#1]
Hotovo úkol 1 i 2, děkuji za kontrolu :)

**Comment by pesikj** [comment]
Ahoj Hedviko,

vzoreček pro precision můžeš odvodit.

Matice Confusion Matrix je

```
[[179  52]
 [ 98  74]]
```

Výpočet pak je 74 / (74 + 52) = 0.5873015873015873.

**Comment by pesikj** [comment]
Jinak super práce :-)
